### PR TITLE
use cmd /c npm.cmd instead of just npm.cmd on windows

### LINKED ISSUE #14: Invoking npm.cmd on Windows is failing
When I run `cargo build` on Windows I get the following error:

```
error: failed to run custom build command for `web v0.1.0 (C:\repositories\rust\myproject\web)`

Caused by:
  process didn't exit successfully: `C:\repositories\rust\myproject\target\debug\build\web-b0554dea23c73a0f\build-script-build` (exit code: 101)
--- stdout
NPM_CMD is npm.cmd
 running npm install npm.cmd in "./assets"

--- stderr
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\repositories\rust\myproject\web\assets\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', web\build.rs:4:5
```

However, the same project compiles just fine on Linux.

The following code reproduced the same error:

```rust
    if let Err(e) = Command::new("npm.cmd")
        .arg("install")
        .current_dir(r#"c:\repositories\rust\myproject\web\assets\"#)
        .status()
    {
        eprintln!("Cannot execute install: {:?}", e);
    }
```
I think it is due to the fact that `npm.cmd` needs to set some variables and probably update PATH prior to running in the command shell. 

The following code seems to work without any problems.

```rust
    if let Err(e) = Command::new("cmd")
        .arg("/c")
        .arg("npm.cmd")
        .arg("install")
        .current_dir(r#"c:\repositories\rust\mdreader\web\assets\"#)
        .status()
    {
        eprintln!("Cannot execute install: {:?}", e);
    }
```

### PR DESCRIPTION
**Pull request by kilork**
fixes #14

### CODE REVIEW

**Comment by kilork** [comment]
Need a windows box to check, looks like we need to add appveyor in the future.

File: src/impl.rs [hunk 1]
```diff
@@ -591,6 +593,16 @@ impl NpmBuild {
...
     }
+
+    #[cfg(not(windows))]
+    fn command(&self) -> Command {
+        Command::new(&self.executable)
+    }
+
+    #[cfg(windows)]
+    fn command(&self) -> Command {
+        Command::new("cmd").arg("/c").arg(&self.executable)
```
Comment (idursun) [inline src/impl.rs]: This doesn't compile on windows:

```
   --> src/impl.rs:604:9
    |
603 |     fn command(&self) -> Command {
    |                          ------- expected `std::process::Command` because of return type
604 |         Command::new("cmd").arg("/c").arg(&self.executable)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::process::Command`, found `&mut std::process::Command`
```

However, the following compiles just fine:

```rust
#[cfg(windows)]
fn command(&self) -> Command {
    let mut cmd = Command::new("cmd");
    cmd.arg("/c").arg(&self.executable);
    cmd
}
```

Comment (kilork) [reply src/impl.rs]: @idursun thanks! I should not develop anything late evening, just taking your code now.

Comment (kilork) [reply src/impl.rs]: checked on my windows machine
